#!/usr/bin/env node

var path = require('path');
var Docker = require('./src/docker.js');
var pwd = process.env.PWD;
var program = require('commander');

program
  .version('0.0.8')
  .option('-i, --input_dir [dir]', 'Input directory (defaults to current dir)', pwd)
  .option('-o, --output_dir [dir]', 'Output directory (defaults to ./doc)', path.join(pwd, 'doc') )
  .option('-u, --updated_files', 'Only process files that have been changed')
  .option('-c, --colour_scheme [style]', 'Colour scheme to use (as in pygmentize -L styles)')
  .parse(process.argv);

var d = new Docker(program.input_dir, program.output_dir, program.updated_files, program.colour_scheme);
if(program.args.length === 0) program.args = ['./'];
d.doc(program.args);
